/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoTyping: typeof import('./src/components/autoTyping.vue')['default']
    ChatWidget: typeof import('./src/components/ChatWidget.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAutoComplete: typeof import('element-plus/es')['ElAutoComplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    UserAddModal: typeof import('./src/components/UsersController/userAddModal.vue')['default']
    UserAddRoleAndPermission: typeof import('./src/components/UsersController/UserAddRoleAndPermission.vue')['default']
    UserAddRoleModal: typeof import('./src/components/UsersController/UserAddRoleModal.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
    UserEdit: typeof import('./src/components/UsersController/userEdit.vue')['default']
    UsersCard: typeof import('./src/components/UserSettingsCards/UsersCard.vue')['default']
    UsersPermissionCard: typeof import('./src/components/UserSettingsCards/UsersPermissionCard.vue')['default']
    UsersRoleCard: typeof import('./src/components/UserSettingsCards/UsersRoleCard.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
